[build]
  publish = "dist"
  command = "yarn run build"

[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Content-Type = "application/xml"

[[headers]]
  for = "/sitemap.xsl"
  [headers.values]
    Content-Type = "application/xml"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 